// ═══════════════════════════════════════════════════════════════════════
//  TEMPLATE ASSETS — placeholder meshes written into a new project folder
//
//  A template that refers to 3dmodels/player.obj is useless until that file
//  exists, and "go and model a character first" is a poor first five minutes.
//  These are generated so a scaffolded project boots and shows something on
//  the first run; replace them with real art whenever.
//
//  OBJ rather than GLTF because it is text, so the whole thing stays inside a
//  self-contained HTML file with no binary blobs. loadOBJ (mesh_loaders.c:57)
//  reads them through fast_obj; with no .mtl alongside, init_vector gives the
//  material a white diffuse, so an untextured mesh is lit normally.
//
//  Sizes are not arbitrary. The Top Down player is a dynamic sphere of radius
//  0.5 whose centre is what physics drives, so the mesh is centred on the
//  origin and one unit tall — a taller mesh would sink through the floor. The
//  same applies to every box here: ODE's GeomBox is centred on the geom's
//  position, so a mesh whose origin sat on its base would draw half its height
//  out of step with the collider.
// ═══════════════════════════════════════════════════════════════════════

/** Accumulates positions, normals and faces into OBJ text. */
class ObjBuilder {
  constructor(name) {
    this.name = name;
    this.v = [];
    this.vn = [];
    this.f = [];
  }

  vertex(x, y, z) { this.v.push([x, y, z]); return this.v.length; }   // OBJ is 1-based
  normal(x, y, z) { this.vn.push([x, y, z]); return this.vn.length; }

  tri(a, b, c, n) { this.f.push([[a, n], [b, n], [c, n]]); }
  quad(a, b, c, d, n) { this.tri(a, b, c, n); this.tri(a, c, d, n); }

  /**
   * Texture coordinates, box-projected per face.
   *
   * Without any `vt` at all a placeholder cannot show a texture — the viewport
   * gives every vertex UV (0,0) and the engine does the same
   * (mesh_loaders.c:48), so an assigned texture samples one texel and reads as
   * a flat colour. That looked like "textures do not work" on meshes the
   * editor itself had written.
   *
   * Each face is projected onto whichever plane it faces and normalised to
   * 0..1 over its own extent, so one face shows the whole image whatever size
   * the mesh is. Placeholder art: the point is to see that a texture is
   * applied, not to be a UV layout anyone would keep.
   */
  faceUVs(face) {
    const [, n] = face[0];
    const nv = this.vn[n - 1];
    const ax = Math.abs(nv[0]), ay = Math.abs(nv[1]), az = Math.abs(nv[2]);
    // Drop the axis the face points along; keep the other two.
    const [i, j] = ax >= ay && ax >= az ? [2, 1] : ay >= az ? [0, 2] : [0, 1];
    const pts = face.map(([vi]) => [this.v[vi - 1][i], this.v[vi - 1][j]]);
    const span = (k) => {
      const vals = pts.map((p) => p[k]);
      const lo = Math.min(...vals), hi = Math.max(...vals);
      return [lo, hi - lo];
    };
    const [u0, du] = span(0), [v0, dv] = span(1);
    return pts.map(([u, v]) => [du > 1e-6 ? (u - u0) / du : 0, dv > 1e-6 ? (v - v0) / dv : 0]);
  }

  toString() {
    const n3 = (p) => p.map((c) => (Math.round(c * 10000) / 10000).toFixed(4)).join(" ");
    const out = [
      `# ${this.name} — placeholder generated by AthEditor.`,
      `# Replace it with your own mesh; the component only refers to the name.`,
      `o ${this.name}`,
    ];
    for (const p of this.v) out.push(`v ${n3(p)}`);

    // One vt per distinct coordinate, so the file does not carry three copies
    // of (0,0) for every face.
    const vt = [];
    const vtIndex = new Map();
    const takeUV = (uv) => {
      const key = `${uv[0].toFixed(4)},${uv[1].toFixed(4)}`;
      if (!vtIndex.has(key)) { vt.push(uv); vtIndex.set(key, vt.length); }
      return vtIndex.get(key);
    };
    const faceRefs = this.f.map((face) => {
      const uvs = this.faceUVs(face);
      return face.map(([vi, ni], k) => `${vi}/${takeUV(uvs[k])}/${ni}`);
    });

    for (const p of vt) out.push(`vt ${n3(p)}`);
    for (const p of this.vn) out.push(`vn ${n3(p)}`);
    for (const refs of faceRefs) out.push(`f ${refs.join(" ")}`);
    return `${out.join("\n")}\n`;
  }
}

/** A closed N-sided prism, capped at both ends. */
function objPrism(b, sides, radius, yBottom, yTop) {
  const up = b.normal(0, 1, 0);
  const down = b.normal(0, -1, 0);
  const bottom = [], top = [], side = [];

  for (let i = 0; i < sides; i++) {
    const a = (i / sides) * Math.PI * 2;
    const x = Math.sin(a) * radius, z = Math.cos(a) * radius;
    bottom.push(b.vertex(x, yBottom, z));
    top.push(b.vertex(x, yTop, z));
    side.push(b.normal(Math.sin(a), 0, Math.cos(a)));
  }
  for (let i = 0; i < sides; i++) {
    const j = (i + 1) % sides;
    b.quad(bottom[i], bottom[j], top[j], top[i], side[i]);
  }
  // Fan the caps from vertex 0. Convex, so a fan is safe.
  for (let i = 1; i < sides - 1; i++) {
    b.tri(top[0], top[i], top[i + 1], up);
    b.tri(bottom[0], bottom[i + 1], bottom[i], down);
  }
  return { bottom, top };
}

/**
 * A blocky stand-in character, one unit tall and centred on the origin.
 *
 * The wedge on +Z matters: the Top Down controller turns the object to face
 * where it is going, and a rotationally symmetric placeholder makes that
 * impossible to see. Forward is +Z in model space because the controller sets
 * rotation.y = atan2(ix, -iz), which is PI when the stick is pushed up.
 */
function playerObj() {
  const b = new ObjBuilder("Player");
  objPrism(b, 8, 0.30, -0.50, 0.16);   // body
  objPrism(b, 6, 0.19, 0.16, 0.50);    // head

  // Nose — a flat wedge pointing along +Z, at eye height.
  const nz = b.normal(0, 0, 1);
  const l = b.vertex(-0.10, 0.36, 0.17);
  const r = b.vertex(0.10, 0.36, 0.17);
  const tip = b.vertex(0.0, 0.30, 0.34);
  b.tri(l, r, tip, nz);
  b.tri(r, l, tip, b.normal(0, 0, -1));

  return b.toString();
}

/** A flat square of ground, centred on the origin at y = 0. */
function groundObj(half = 10) {
  const b = new ObjBuilder("Ground");
  const n = b.normal(0, 1, 0);
  const a = b.vertex(-half, 0, -half);
  const c = b.vertex(half, 0, -half);
  const d = b.vertex(half, 0, half);
  const e = b.vertex(-half, 0, half);
  b.quad(a, e, d, c, n);   // wound so the visible face points up
  return b.toString();
}

/**
 * A closed box centred on the origin, with one normal per face so the six
 * sides shade differently and the shape reads as solid.
 *
 * Centred, not sitting on its base, because a Rigidbody's geom is placed at the
 * object's position and a GeomBox is centred on it — a mesh with its origin at
 * the base would draw half a unit out of step with the collider.
 */
function boxObj(name, sx, sy, sz) {
  const b = new ObjBuilder(name);
  const x = sx / 2, y = sy / 2, z = sz / 2;
  // 0..3 bottom (-Y), 4..7 top (+Y), each ring wound counter-clockwise from -X-Z.
  const v = [
    b.vertex(-x, -y, -z), b.vertex(x, -y, -z), b.vertex(x, -y, z), b.vertex(-x, -y, z),
    b.vertex(-x, y, -z), b.vertex(x, y, -z), b.vertex(x, y, z), b.vertex(-x, y, z),
  ];
  b.quad(v[7], v[6], v[5], v[4], b.normal(0, 1, 0));    // top
  b.quad(v[0], v[1], v[2], v[3], b.normal(0, -1, 0));   // bottom
  b.quad(v[3], v[2], v[6], v[7], b.normal(0, 0, 1));    // +Z
  b.quad(v[1], v[0], v[4], v[5], b.normal(0, 0, -1));   // -Z
  b.quad(v[2], v[1], v[5], v[6], b.normal(1, 0, 0));    // +X
  b.quad(v[0], v[3], v[7], v[4], b.normal(-1, 0, 0));   // -X
  return b.toString();
}

/** A one-unit crate. Scenery, and something to walk into. */
const crateObj = () => boxObj("Crate", 1, 1, 1);

/**
 * A side-scroller platform: wide enough to land on, deep enough to read as a
 * solid from the fixed side view. Its extents are what the template gives the
 * box collider, so the two must be changed together.
 */
const platformObj = () => boxObj("Platform", 4, 0.5, 2);

/** Placeholder meshes by file name — the one place a template's `needs` resolves. */
const TEMPLATE_MESHES = {
  "player.obj": playerObj,
  "ground.obj": groundObj,
  "crate.obj": crateObj,
  "platform.obj": platformObj,
};

/**
 * Files a template wants on disk, as { path, text }. Paths are relative to the
 * project folder and use the project's own directory names.
 */
function templateAssetFiles(project, names = []) {
  const models = project.dirs?.models || "3dmodels";
  return names
    .filter((n) => TEMPLATE_MESHES[n])
    .map((n) => ({ path: `${models}/${n}`, text: TEMPLATE_MESHES[n]() }));
}
