// ═══════════════════════════════════════════════════════════════════════
//  TEMPLATE — First Person
//
//  The camera IS the player: a dynamic sphere you never see, with the view
//  taken from a point above its centre. Left stick walks, right stick looks,
//  ✕ jumps.
//
//  Three decisions here are engine constraints rather than taste:
//
//   * The Player has no Model. In first person the mesh would sit inside the
//     near plane and be clipped away every frame for nothing. codegen only
//     reports a model-less dynamic body when nothing scripts it, so this
//     costs no diagnostic.
//   * Freeze Rotation is on. A sphere with a free rotation would spin under
//     the contact solver, and the yaw the camera uses is the script's, not
//     the body's.
//   * The scene's orbit rig is off, or the built-in left-stick camera and
//     this controller would both write the camera every frame.
//
//  Crates are scenery with a purpose: on a flat, untextured plane under one
//  directional light there is no parallax at all, so walking looks identical
//  to standing still and the template reads as broken.
// ═══════════════════════════════════════════════════════════════════════

const FIRSTPERSON_CONTROLLER = `// FirstPersonController.js — generated by the First Person template.
//
// ctx.player is this object's own state slot. The only engine handle it needs
// is ctx.physics.bodies.player: there is no RenderObject, because the thing
// this script drives is the camera.

const DEADZONE = 25;      // sticks rest near 0 but are never exactly 0
const STICK_MAX = 127.0;

// Past about 80 degrees the view vector is nearly parallel to the camera's up
// vector and the look-at matrix loses its horizon. Stop short of it.
const PITCH_LIMIT = 1.35;

/** A stick axis as -1..1, with the rest position filtered out. */
function axis(v) {
    return (v > DEADZONE || v < -DEADZONE) ? v / STICK_MAX : 0.0;
}

export function init(ctx) {
    const s = ctx.player;
    s.yaw = 0.0;            // 0 looks along -Z, the direction the scene faces
    s.pitch = 0.0;          // radians, positive looks up
    s.speed = 5.0;          // world units per second
    s.lookRate = 2.6;       // radians per second at full stick
    s.jumpSpeed = 4.6;
    s.eyeHeight = 1.25;     // above the body's centre, not above the ground
    s.grounded = false;
}

export function update(ctx, pad) {
    const s = ctx.player;
    const body = ctx.physics.bodies.player;

    // ── grounded ────────────────────────────────────────────────────
    // ode_onCollide stored the contact normal from the last step, so no extra
    // raycast is needed. Only its steepness is meaningful: ODE's normal points
    // into whichever geom the broad phase happened to call the first one, so
    // the sign is not ours to rely on — hence the abs().
    const n = s.lastHitNormal;
    s.grounded = !!n && Math.abs(n[1]) > 0.7;
    s.lastHitNormal = null;     // consume it, or one contact grounds you forever

    // ── look ────────────────────────────────────────────────────────
    // Turning right decreases yaw: forward is (-sin yaw, 0, -cos yaw), so
    // world +X — the right-hand side of the screen — sits at yaw = -PI/2.
    let turn = axis(pad.rx);
    if (pad.pressed(Pads.L1)) turn = -1.0;   // fallback for a digital pad
    if (pad.pressed(Pads.R1)) turn =  1.0;
    s.yaw -= turn * s.lookRate * ctx.dt;
    // pad.ry grows downwards (it is rjoy_v - 127), so push-up must raise the aim.
    s.pitch -= axis(pad.ry) * s.lookRate * ctx.dt;
    if (s.pitch >  PITCH_LIMIT) s.pitch =  PITCH_LIMIT;
    if (s.pitch < -PITCH_LIMIT) s.pitch = -PITCH_LIMIT;

    const sy = Math.sin(s.yaw), cy = Math.cos(s.yaw);
    const fx = -sy, fz = -cy;   // forward, flattened onto the ground plane
    const rx =  cy, rz = -sy;   // right

    // ── move ────────────────────────────────────────────────────────
    let ix = axis(pad.lx);      // strafe
    let iz = -axis(pad.ly);     // forward; pad.ly grows downwards too
    if (pad.pressed(Pads.LEFT))  ix = -1.0;
    if (pad.pressed(Pads.RIGHT)) ix =  1.0;
    if (pad.pressed(Pads.UP))    iz =  1.0;
    if (pad.pressed(Pads.DOWN))  iz = -1.0;

    // Clamp to the unit circle so diagonals are not faster.
    const mag = Math.sqrt(ix * ix + iz * iz);
    if (mag > 1.0) { ix /= mag; iz /= mag; }

    // Drive velocity directly and leave Y to gravity, except on the frame the
    // jump starts. Reading the current Y back keeps the fall going.
    const vel = body.getLinearVel();
    let vy = vel[1];
    if (s.grounded && pad.justPressed(Pads.CROSS)) vy = s.jumpSpeed;
    body.setLinearVel((fx * iz + rx * ix) * s.speed, vy, (fz * iz + rz * ix) * s.speed);

    // ── camera ──────────────────────────────────────────────────────
    // The scene's orbit rig is off, so nothing else writes the camera.
    // Target BEFORE position: Camera.target() moves the camera by the same
    // delta to preserve the view vector (setCameraTarget in src/camera.c), so
    // calling it second would drag the eye that was just placed.
    const p = body.getPosition();
    const ex = p[0], ey = p[1] + s.eyeHeight, ez = p[2];
    const cp = Math.cos(s.pitch), sp = Math.sin(s.pitch);
    Camera.target(ex + fx * cp * 10.0, ey + sp * 10.0, ez + fz * cp * 10.0);
    Camera.position(ex, ey, ez);
}
`;

function templateFirstPerson() {
  const project = mkProject("FirstPersonGame");
  project.template = "first-person";
  project.scripts = [{ name: "FirstPersonController.js", content: FIRSTPERSON_CONTROLLER }];

  const scene = project.scenes[0];
  scene.name = "Level1";
  scene.background = { r: 30, g: 36, b: 46, a: 128 };
  scene.physics = { ...scene.physics, enabled: true, gravity: { x: 0, y: -9.81, z: 0 } };
  // The controller owns the camera.
  scene.defaultCameraRig = false;
  // A near plane of 1.0 — the editor's default — would hide anything within a
  // metre of the eye, so you could walk into a crate and see through it.
  scene.camera = { fov: 65, near: 0.4, far: 2000.0 };

  const sun = mkObject("Sun");
  sun.components.light = Object.assign(makeComponent("light"), {
    direction: v3(0.5, 1, 0.35),
    ambient: rgb(0.24, 0.25, 0.3),
    diffuse: rgb(0.62, 0.6, 0.55),
  });

  // Placed where the controller will put it on the first frame, so the scene
  // as exported and the scene as played open on the same view.
  const camera = mkObject("Main Camera");
  camera.components.camera = Object.assign(makeComponent("camera"), {
    fov: 65, near: 0.4, far: 2000.0, target: v3(0, 1.65, -6),
  });
  camera.components.transform.position = v3(0, 1.65, 4);

  const ground = mkObject("Ground");
  ground.components.model = Object.assign(makeComponent("model"), { file: "ground.obj" });
  ground.components.rigidbody = Object.assign(makeComponent("rigidbody"), {
    mode: "static", shape: "plane", planeY: 0,
  });

  const player = mkObject("Player");
  player.components.transform.position = v3(0, 1, 4);
  player.components.rigidbody = Object.assign(makeComponent("rigidbody"), {
    // Mass 5, not a person's 70. The engine's contact is a spring of fixed
    // softness (soft_cfm 0.01, ath_ode.c:825) with no binding to stiffen it,
    // so penetration grows with mass: measured on PCSX2, a sphere sinks about
    // 2 mm per unit of mass. At 70 the eye would sit 14 cm into the floor and
    // jitter. See docs/HARDWARE-NOTES.md.
    mode: "dynamic", shape: "sphere", radius: 0.4, mass: 5,
    autoFit: false, freezeRotation: true,
    collisionEvents: true, onCollide: "player",
  });
  player.components.script = Object.assign(makeComponent("script"), {
    file: "FirstPersonController.js", ctxKey: "player",
  });

  // Landmarks. They share one RenderData because their Model settings match,
  // so four crates cost one mesh upload.
  const crateAt = (name, x, y, z) => {
    const o = mkObject(name);
    o.components.model = Object.assign(makeComponent("model"), { file: "crate.obj" });
    o.components.transform.position = v3(x, y, z);
    o.components.rigidbody = Object.assign(makeComponent("rigidbody"), {
      mode: "static", shape: "box", autoFit: false, size: v3(1, 1, 1),
    });
    return o;
  };

  scene.objects = [
    sun, camera, ground, player,
    crateAt("Crate1", 3, 0.5, -3),
    crateAt("Crate2", -4, 0.5, -1),
    crateAt("Crate3", -1, 0.5, -7),
    crateAt("Crate4", 3, 1.5, -3),   // stacked on Crate1
  ];
  return project;
}
