// ═══════════════════════════════════════════════════════════════════════
//  TEMPLATE — Third Person
//
//  A character on the ground with the camera orbiting behind them. Left stick
//  moves relative to where the camera is looking, right stick swings the
//  camera around, ✕ jumps.
//
//  The two angles are deliberately separate and it matters which is which:
//
//   * `s.yaw` is the CAMERA's. Movement is resolved against it, which is what
//     makes "push up" mean "away from the camera" no matter where the camera
//     has been swung to.
//   * `s.angle` is the MODEL's, and only chases the direction of travel. If
//     the model turned with the camera the character would moonwalk.
//
//  Freeze Rotation is on for the same reason as in Top Down: without it the
//  physics sync overwrites the visual rotation every frame and the character
//  rolls like a marble. The scene's orbit rig is off so it cannot fight the
//  script for the camera.
// ═══════════════════════════════════════════════════════════════════════

const THIRDPERSON_CONTROLLER = `// ThirdPersonController.js — generated by the Third Person template.
//
// ctx.player is this object's own state slot. The engine handles it reaches
// are ctx.physics.bodies.player (the ODE body) and ctx.RenderObjects.player
// (what is drawn).

const DEADZONE = 25;      // sticks rest near 0 but are never exactly 0
const STICK_MAX = 127.0;

// The camera must stay off the poles: at 90 degrees the view vector lines up
// with the camera's up vector and the look-at matrix has no horizon left.
const PITCH_MIN = -0.2;
const PITCH_MAX = 1.2;

/** A stick axis as -1..1, with the rest position filtered out. */
function axis(v) {
    return (v > DEADZONE || v < -DEADZONE) ? v / STICK_MAX : 0.0;
}

export function init(ctx) {
    const s = ctx.player;
    s.yaw = 0.0;            // camera angle. 0 puts the camera on +Z, looking at -Z
    s.pitch = 0.35;         // radians above the character
    s.angle = Math.PI;      // model facing: PI points its +Z nose along world -Z
    s.speed = 6.0;          // world units per second
    s.turnRate = 12.0;      // how quickly the character swings around
    s.lookRate = 2.4;       // radians per second at full stick
    s.jumpSpeed = 5.2;
    s.camDistance = 8.0;
    s.camHeight = 1.5;      // where the camera looks, above the body centre
    s.grounded = false;
}

export function update(ctx, pad) {
    const s = ctx.player;
    const body = ctx.physics.bodies.player;
    const view = ctx.RenderObjects.player;

    // ── grounded ────────────────────────────────────────────────────
    // ode_onCollide stored the contact normal from the last step. Only its
    // steepness is meaningful: ODE's normal points into whichever geom the
    // broad phase called the first one, so the sign is not ours to rely on.
    const n = s.lastHitNormal;
    s.grounded = !!n && Math.abs(n[1]) > 0.7;
    s.lastHitNormal = null;     // consume it, or one contact grounds you forever

    // ── swing the camera ────────────────────────────────────────────
    // Turning right decreases yaw: forward is (-sin yaw, 0, -cos yaw), so
    // world +X — the right-hand side of the screen — sits at yaw = -PI/2.
    let turn = axis(pad.rx);
    if (pad.pressed(Pads.L1)) turn = -1.0;   // fallback for a digital pad
    if (pad.pressed(Pads.R1)) turn =  1.0;
    s.yaw -= turn * s.lookRate * ctx.dt;
    // pad.ry grows downwards (it is rjoy_v - 127), and pitch is the camera's
    // elevation, so adding it means pushing the stick up drops the camera and
    // aims the view upward — the same gesture as in first person.
    s.pitch += axis(pad.ry) * s.lookRate * ctx.dt;
    if (s.pitch > PITCH_MAX) s.pitch = PITCH_MAX;
    if (s.pitch < PITCH_MIN) s.pitch = PITCH_MIN;

    const sy = Math.sin(s.yaw), cy = Math.cos(s.yaw);
    const fx = -sy, fz = -cy;   // where the camera looks, flattened
    const rx =  cy, rz = -sy;   // its right

    // ── move, relative to the camera ────────────────────────────────
    let ix = axis(pad.lx);
    let iz = -axis(pad.ly);     // pad.ly grows downwards, so negate for "forward"
    if (pad.pressed(Pads.LEFT))  ix = -1.0;
    if (pad.pressed(Pads.RIGHT)) ix =  1.0;
    if (pad.pressed(Pads.UP))    iz =  1.0;
    if (pad.pressed(Pads.DOWN))  iz = -1.0;

    // Clamp to the unit circle so diagonals are not faster.
    const mag = Math.sqrt(ix * ix + iz * iz);
    if (mag > 1.0) { ix /= mag; iz /= mag; }

    const mx = fx * iz + rx * ix;   // world direction of travel
    const mz = fz * iz + rz * ix;

    const vel = body.getLinearVel();
    let vy = vel[1];
    if (s.grounded && pad.justPressed(Pads.CROSS)) vy = s.jumpSpeed;
    body.setLinearVel(mx * s.speed, vy, mz * s.speed);

    // ── face the direction of travel ────────────────────────────────
    // rotation.y = T sends the model's +Z axis to (sin T, cos T), so the angle
    // that points its nose along (mx, mz) is atan2(mx, mz).
    // Freeze Rotation keeps the solver from touching this.
    if (mag > 0.15) {
        const want = Math.atan2(mx, mz);
        let delta = want - s.angle;
        while (delta >  Math.PI) delta -= Math.PI * 2.0;
        while (delta < -Math.PI) delta += Math.PI * 2.0;
        s.angle += delta * Math.min(1.0, s.turnRate * ctx.dt);
        view.rotation = { x: 0.0, y: s.angle, z: 0.0 };
    }

    // ── camera ──────────────────────────────────────────────────────
    // Straight back along the camera's own forward vector, lifted by pitch.
    // Target BEFORE position: Camera.target() moves the camera by the same
    // delta to preserve the view vector (setCameraTarget in src/camera.c), so
    // calling it second would drag the position that was just set.
    const p = body.getPosition();
    const tx = p[0], ty = p[1] + s.camHeight, tz = p[2];
    const back = s.camDistance * Math.cos(s.pitch);
    Camera.target(tx, ty, tz);
    Camera.position(tx - fx * back, ty + s.camDistance * Math.sin(s.pitch), tz - fz * back);
}
`;

function templateThirdPerson() {
  const project = mkProject("ThirdPersonGame");
  project.template = "third-person";
  project.scripts = [{ name: "ThirdPersonController.js", content: THIRDPERSON_CONTROLLER }];

  const scene = project.scenes[0];
  scene.name = "Level1";
  scene.background = { r: 26, g: 34, b: 44, a: 128 };
  scene.physics = { ...scene.physics, enabled: true, gravity: { x: 0, y: -9.81, z: 0 } };
  // The controller owns the camera.
  scene.defaultCameraRig = false;
  scene.camera = { fov: 55, near: 1.0, far: 4000.0 };

  const sun = mkObject("Sun");
  sun.components.light = Object.assign(makeComponent("light"), {
    direction: v3(0.45, 1, 0.5),
    ambient: rgb(0.22, 0.24, 0.3),
    diffuse: rgb(0.66, 0.63, 0.56),
  });

  // Where the controller puts it on the first frame: behind the player at
  // yaw 0, lifted by the starting pitch.
  const camera = mkObject("Main Camera");
  camera.components.camera = Object.assign(makeComponent("camera"), {
    fov: 55, target: v3(0, 2.0, 0),
  });
  camera.components.transform.position = v3(0, 4.75, 7.51);

  const ground = mkObject("Ground");
  ground.components.model = Object.assign(makeComponent("model"), { file: "ground.obj" });
  ground.components.rigidbody = Object.assign(makeComponent("rigidbody"), {
    mode: "static", shape: "plane", planeY: 0,
  });

  const player = mkObject("Player");
  player.components.model = Object.assign(makeComponent("model"), { file: "player.obj" });
  player.components.transform.position = v3(0, 1, 0);
  player.components.rigidbody = Object.assign(makeComponent("rigidbody"), {
    // Mass 5, not a person's 70 — the engine's contact softness is fixed and
    // penetration grows with mass. See docs/HARDWARE-NOTES.md.
    mode: "dynamic", shape: "sphere", radius: 0.5, mass: 5,
    autoFit: false, freezeRotation: true,
    collisionEvents: true, onCollide: "player",
  });
  player.components.script = Object.assign(makeComponent("script"), {
    file: "ThirdPersonController.js", ctxKey: "player",
  });

  scene.objects = [sun, camera, ground, player];
  return project;
}
