// ═══════════════════════════════════════════════════════════════════════
//  TEMPLATE — Top Down
//
//  A camera looking down at a character that moves on the XZ plane and turns
//  to face where it is going.
//
//  Three details make this work, and each of them is a real engine
//  constraint rather than a preference:
//
//   * The Rigidbody has Freeze Rotation on. Without it the physics sync
//     overwrites the visual rotation every frame and the character spins
//     like a marble.
//   * The scene's orbit rig is off. The built-in left-stick camera and the
//     controller would otherwise both drive the camera each frame.
//   * pad.ly is positive when the stick is pushed DOWN (it is ljoy_v - 127),
//     so forward is -ly. See ath_pads.c.
//
//  The mesh names below are a convention. If they are not in the asset
//  folder the Problems panel says so — assign your own in the Inspector.
// ═══════════════════════════════════════════════════════════════════════

const TOPDOWN_CONTROLLER = `// TopDownController.js — generated by the Top Down template.
//
// ctx.player is this object's own state slot. The engine handles it reaches
// are ctx.physics.bodies.player (the ODE body) and ctx.RenderObjects.player
// (what is drawn).

const DEADZONE = 25;      // sticks rest near 0 but are never exactly 0
const STICK_MAX = 127.0;

export function init(ctx) {
    const s = ctx.player;
    s.speed = 6.0;          // world units per second
    s.turnRate = 12.0;      // how quickly the character swings around
    s.angle = 0.0;
    s.camHeight = 13.0;
    s.camDistance = 9.0;
}

export function update(ctx, pad) {
    const s = ctx.player;
    const body = ctx.physics.bodies.player;
    const view = ctx.RenderObjects.player;

    // ── read the stick, fall back to the d-pad ──────────────────────
    let ix = (pad.lx > DEADZONE || pad.lx < -DEADZONE) ? pad.lx / STICK_MAX : 0.0;
    // pad.ly grows downwards, so negate it to get "forward".
    let iz = (pad.ly > DEADZONE || pad.ly < -DEADZONE) ? -pad.ly / STICK_MAX : 0.0;

    if (pad.pressed(Pads.LEFT))  ix = -1.0;
    if (pad.pressed(Pads.RIGHT)) ix =  1.0;
    if (pad.pressed(Pads.UP))    iz =  1.0;
    if (pad.pressed(Pads.DOWN))  iz = -1.0;

    // Clamp to the unit circle so diagonals are not faster.
    const mag = Math.sqrt(ix * ix + iz * iz);
    if (mag > 1.0) { ix /= mag; iz /= mag; }

    // ── move ────────────────────────────────────────────────────────
    // Drive velocity directly and leave Y to gravity. Forward on the stick
    // means -Z, which is the direction the camera looks.
    const vel = body.getLinearVel();
    body.setLinearVel(ix * s.speed, vel[1], -iz * s.speed);

    // ── face the direction of travel ────────────────────────────────
    // Freeze Rotation keeps the solver from touching this.
    if (mag > 0.15) {
        const want = Math.atan2(ix, -iz);
        let delta = want - s.angle;
        while (delta >  Math.PI) delta -= Math.PI * 2.0;
        while (delta < -Math.PI) delta += Math.PI * 2.0;
        s.angle += delta * Math.min(1.0, s.turnRate * ctx.dt);
        view.rotation = { x: 0.0, y: s.angle, z: 0.0 };
    }

    // ── camera ──────────────────────────────────────────────────────
    // The scene's orbit rig is off, so nothing else writes the camera.
    // Target BEFORE position: Camera.target() moves the camera by the same
    // delta to preserve the view vector (setCameraTarget in src/camera.c), so
    // calling it second would drag the position that was just set.
    const p = view.position;
    Camera.target(p.x, p.y, p.z);
    Camera.position(p.x, p.y + s.camHeight, p.z + s.camDistance);
}
`;

function templateTopDown() {
  const project = mkProject("TopDownGame");
  project.template = "top-down";
  project.scripts = [{ name: "TopDownController.js", content: TOPDOWN_CONTROLLER }];

  const scene = project.scenes[0];
  scene.name = "Level1";
  scene.background = { r: 24, g: 30, b: 42, a: 128 };
  scene.physics = { ...scene.physics, enabled: true, gravity: { x: 0, y: -9.81, z: 0 } };
  // The controller owns the camera.
  scene.defaultCameraRig = false;
  scene.camera = { fov: 50, near: 1.0, far: 4000.0 };

  const sun = mkObject("Sun");
  sun.components.light = Object.assign(makeComponent("light"), {
    direction: v3(0.4, 1, 0.6),
    ambient: rgb(0.22, 0.24, 0.3),
    diffuse: rgb(0.65, 0.62, 0.55),
  });

  const camera = mkObject("Main Camera");
  camera.components.camera = Object.assign(makeComponent("camera"), { fov: 50 });
  camera.components.transform.position = v3(0, 13, 9);

  const ground = mkObject("Ground");
  ground.components.model = Object.assign(makeComponent("model"), { file: "ground.obj" });
  ground.components.rigidbody = Object.assign(makeComponent("rigidbody"), {
    mode: "static", shape: "plane", planeY: 0,
  });

  const player = mkObject("Player");
  player.components.model = Object.assign(makeComponent("model"), { file: "player.obj" });
  player.components.transform.position = v3(0, 1, 0);
  player.components.rigidbody = Object.assign(makeComponent("rigidbody"), {
    // Mass 5, not a person's 60. Measured on PCSX2: the engine's contact is a
    // spring of fixed softness (soft_cfm 0.01, ath_ode.c:825), so a sphere
    // sinks about 2 mm per unit of mass — at 60 the character stood 12 cm into
    // the floor and jittered. See docs/HARDWARE-NOTES.md.
    mode: "dynamic", shape: "sphere", radius: 0.5, mass: 5,
    autoFit: false, freezeRotation: true,
    collisionEvents: true, onCollide: "player",
  });
  player.components.script = Object.assign(makeComponent("script"), {
    file: "TopDownController.js", ctxKey: "player",
  });

  scene.objects = [sun, camera, ground, player];
  return project;
}
