import { assert, assertEquals } from "jsr:@std/assert@1";
import { load } from "./_load.js";

const A = await load(["core/util.js", "core/fsaccess.js"]);

// ── a stand-in for the File System Access API ──────────────────────────
// The real picker is a native dialog that cannot be driven from a test, but
// everything after it is ordinary async calls against handles.
function mockDir(name = "sampleproject", seed = {}) {
  const files = new Map(Object.entries(seed));   // "scripts/A.js" -> contents
  const dirs = new Set();
  // A seeded file implies its directory exists, as it would on a real disk.
  for (const path of files.keys()) {
    const parts = path.split("/");
    for (let i = 1; i < parts.length; i++) dirs.add(`${parts.slice(0, i).join("/")}/`);
  }

  const makeHandle = (prefix) => ({
    kind: "directory",
    name: prefix ? prefix.replace(/\/$/, "") : name,
    async getDirectoryHandle(child, opts) {
      const path = `${prefix}${child}/`;
      if (!dirs.has(path) && !opts?.create) throw new DOMException("Missing file", "NotFoundError");
      dirs.add(path);
      return makeHandle(path);
    },
    async getFileHandle(child, opts) {
      const path = `${prefix}${child}`;
      if (!files.has(path) && !opts?.create) throw new DOMException("Missing file", "NotFoundError");
      return {
        kind: "file",
        name: child,
        async getFile() {
          if (!files.has(path)) throw new DOMException("Missing file", "NotFoundError");
          return { text: async () => typeof files.get(path)==="string"?files.get(path):new TextDecoder().decode(files.get(path)), arrayBuffer: async () => new Blob([files.get(path)]).arrayBuffer() };
        },
        async createWritable() {
          let buf = "";
          return {
            write: async (chunk) => { buf = typeof chunk === "string" ? buf + chunk : chunk; },
            close: async () => { files.set(path, buf); },
          };
        },
      };
    },
  });

  const root = makeHandle("");
  // Scaffolding asks whether the folder is empty, which walks entries().
  root.entries = async function* () {
    const top = new Set();
    for (const p of files.keys()) top.add(p.split("/")[0]);
    for (const d of dirs) top.add(d.split("/")[0]);
    for (const name of top) yield [name, { kind: files.has(name) ? "file" : "directory" }];
  };
  return { root, files, dirs };
}

const exportResult = (extra = {}) => ({
  main: "// Generated by AthEditor\nwhile (true) {}\n",
  scripts: [{ filename: "scripts/TopDownController.js", content: "export function init(ctx) {}\n" }],
  ...extra,
});

Deno.test("export writes main.js and creates the scripts folder", async () => {
  const { root, files, dirs } = mockDir();
  const out = await A.fsWriteExport(root, exportResult());

  assertEquals(out.skipped, false);
  assertEquals(out.written, ["main.js", "scripts/TopDownController.js"]);
  assert(files.has("main.js"));
  assert(files.get("main.js").includes("while (true)"));
  assert(files.has("scripts/TopDownController.js"));
  assert(dirs.has("scripts/"), "the scripts directory was not created");
});

Deno.test("a configured scripts folder is honoured", async () => {
  const { root, files, dirs } = mockDir();
  await A.fsWriteExport(root, exportResult({
    scripts: [{ filename: "src/Hero.js", content: "export function init(ctx) {}\n" }],
  }));
  assert(files.has("src/Hero.js"));
  assert(dirs.has("src/"));
});

Deno.test("overwriting our own previous output needs no confirmation", async () => {
  const { root, files } = mockDir("sampleproject", {
    "main.js": "// Generated by the AthenaEnv Level Editor\n// old build\n",
  });
  let asked = false;
  const out = await A.fsWriteExport(root, exportResult(), {
    confirmOverwrite: async () => { asked = true; return true; },
  });
  assertEquals(asked, false, "asked before replacing a file it wrote itself");
  assertEquals(out.skipped, false);
  assert(files.get("main.js").includes("while (true)"));
});

Deno.test("an empty main.js is replaced without asking", async () => {
  // This is the state a fresh AthenaEnv folder ships in.
  const { root, files } = mockDir("sampleproject", { "main.js": "" });
  let asked = false;
  await A.fsWriteExport(root, exportResult(), {
    confirmOverwrite: async () => { asked = true; return true; },
  });
  assertEquals(asked, false);
  assert(files.get("main.js").includes("while (true)"));
});

Deno.test("scene export preflights every destination before touching a handwritten level", async () => {
  const { root, files } = mockDir("game", { "scene_2.js": "// handwritten level" });
  const before = [...files.entries()];
  const result = exportResult({ sceneFiles: [{ filename: "scene_2.js", content: "// Generated by AthEditor\n" }] });
  const skipped = await A.fsWriteExport(root, result, { confirmOverwrite: async conflicts => {
    assertEquals(conflicts, [{ path: "scene_2.js", kind: "handwritten" }]);
    return false;
  } });
  assert(skipped.skipped);
  assertEquals([...files.entries()], before);
  await A.fsWriteExport(root, result, { confirmOverwrite: async () => true });
  assert(files.has("main.js"));
  assertEquals(files.get("scene_2.js"), result.sceneFiles[0].content);
});

Deno.test("AthEditor recognizes its renamed export marker", async () => {
  const { root } = mockDir("sampleproject", { "main.js": "// Generated by AthEditor\n// previous export" });
  const out = await A.fsWriteExport(root, exportResult(), {
    confirmOverwrite: async () => { throw Error("generated output should not prompt"); },
  });
  assertEquals(out.skipped, false);
  assert(out.written.includes("main.js"));
});

Deno.test("a hand-written main.js is protected", async () => {
  const handWritten = "// my own game\nScreen.setMode(Screen.getMode());\n";
  const { root, files } = mockDir("sampleproject", { "main.js": handWritten });

  let offered = null;
  const out = await A.fsWriteExport(root, exportResult(), {
    confirmOverwrite: async (conflicts) => { offered = conflicts; return false; },
  });

  assertEquals(offered, [{ path: "main.js", kind: "handwritten" }]);
  assertEquals(out.skipped, true);
  assertEquals(out.written, []);
  assertEquals(files.get("main.js"), handWritten, "declining still overwrote the file");
});

Deno.test("a script that already matches is neither rewritten nor queried", async () => {
  // The generator reads behaviour scripts back off disk, so on a normal export
  // they are identical. Prompting every time trained people to click through
  // the one prompt that actually matters.
  const result = exportResult();
  const { root, files } = mockDir("sampleproject", {
    "main.js": "// Generated by the AthenaEnv Level Editor\n// old build\n",
    "scripts/TopDownController.js": result.scripts[0].content,
  });

  let asked = false;
  const out = await A.fsWriteExport(root, result, {
    confirmOverwrite: async () => { asked = true; return true; },
  });

  assertEquals(asked, false, "asked about a file that is already identical");
  assertEquals(out.written, ["main.js"]);
  assertEquals(out.unchanged, ["scripts/TopDownController.js"]);
  assertEquals(files.get("scripts/TopDownController.js"), result.scripts[0].content);
});

Deno.test("an export with nothing to do writes nothing at all", async () => {
  const result = exportResult();
  const { root } = mockDir("sampleproject", {
    "main.js": result.main,
    "scripts/TopDownController.js": result.scripts[0].content,
  });
  const out = await A.fsWriteExport(root, result, {
    confirmOverwrite: async () => { throw new Error("must not ask"); },
  });
  assertEquals(out.written, []);
  assertEquals(out.unchanged, ["main.js", "scripts/TopDownController.js"]);
  assertEquals(out.skipped, false);
});

Deno.test("a script edited on disk is flagged as an edit, not as foreign", async () => {
  const { root } = mockDir("sampleproject", {
    "main.js": "// Generated by the AthenaEnv Level Editor\n",
    "scripts/TopDownController.js": "export function init(ctx) { /* my tweak */ }\n",
  });
  let offered = null;
  await A.fsWriteExport(root, exportResult(), {
    confirmOverwrite: async (conflicts) => { offered = conflicts; return false; },
  });
  assertEquals(offered, [{ path: "scripts/TopDownController.js", kind: "edited" }]);
});

Deno.test("declining aborts everything, not just the conflicting file", async () => {
  const { root, files } = mockDir("sampleproject", { "main.js": "// mine\n" });
  await A.fsWriteExport(root, exportResult(), { confirmOverwrite: async () => false });
  assert(!files.has("scripts/TopDownController.js"), "a partial export was written");
});

Deno.test("confirming replaces every listed file", async () => {
  const { root, files } = mockDir("sampleproject", {
    "main.js": "// mine\n",
    "scripts/TopDownController.js": "// also mine\n",
  });
  const out = await A.fsWriteExport(root, exportResult(), { confirmOverwrite: async () => true });
  assertEquals(out.written.length, 2);
  assert(files.get("main.js").includes("while (true)"));
  assert(files.get("scripts/TopDownController.js").includes("export function init"));
});

Deno.test("every conflicting file is listed, not just the first", async () => {
  const { root } = mockDir("sampleproject", {
    "main.js": "// mine\n",
    "scripts/TopDownController.js": "// mine too\n",
  });
  let offered = null;
  await A.fsWriteExport(root, exportResult(), {
    confirmOverwrite: async (conflicts) => { offered = conflicts; return false; },
  });
  assertEquals(offered.map((c) => c.path), ["main.js", "scripts/TopDownController.js"]);
});

Deno.test("a missing file reads as absent rather than throwing", async () => {
  const { root } = mockDir();
  assertEquals(await A.fsReadTextIfPresent(root, "nope.js"), null);
  assertEquals(await A.fsReadTextIfPresent(root, "deep/nope.js"), null);
});

Deno.test("plain writes go where they are told", async () => {
  const { root, files } = mockDir();
  await A.fsWriteText(root, "topdowngame.athena.json", '{"name":"x"}');
  assertEquals(files.get("topdowngame.athena.json"), '{"name":"x"}');
});

// ═══════════════════════════════════════════════════════════════════════
//  Scaffolding a new project folder
// ═══════════════════════════════════════════════════════════════════════

const samplePlan = () => ({
  dirs: ["3dmodels", "textures", "scripts"],
  files: [
    { path: "athena.ini", text: 'default_script = "main.js"\n' },
    { path: "3dmodels/player.obj", text: "o Player\n" },
    { path: "scripts/TopDownController.js", text: "export function init(ctx) {}\n" },
    { path: "mygame.athena.json", text: '{"name":"MyGame"}' },
  ],
});

Deno.test("scaffolding creates the directories and writes every planned file", async () => {
  const { root, files, dirs } = mockDir("newgame");
  const out = await A.fsScaffoldProject(root, samplePlan());

  for (const d of ["3dmodels/", "textures/", "scripts/"]) {
    assert(dirs.has(d), `${d} was not created`);
  }
  assertEquals(out.skipped, []);
  assertEquals(out.written.length, 4);
  assertEquals(files.get("mygame.athena.json"), '{"name":"MyGame"}');
});

Deno.test("an empty asset directory is still created", async () => {
  // textures/ has no files in the plan. Without it the folder layout is
  // incomplete and os.chdir("textures") fails on hardware.
  const { root, dirs } = mockDir("newgame");
  await A.fsScaffoldProject(root, samplePlan());
  assert(dirs.has("textures/"));
});

Deno.test("scaffolding never overwrites a file that is already there", async () => {
  const { root, files } = mockDir("existinggame", {
    "athena.ini": "# my own settings\n",
    "3dmodels/player.obj": "o MyRealCharacter\n",
  });
  const out = await A.fsScaffoldProject(root, samplePlan());

  assertEquals(out.skipped, ["athena.ini", "3dmodels/player.obj"]);
  assertEquals(files.get("athena.ini"), "# my own settings\n", "an existing ini was replaced");
  assertEquals(files.get("3dmodels/player.obj"), "o MyRealCharacter\n", "real art was replaced");
  assert(files.has("scripts/TopDownController.js"), "the rest of the scaffold was skipped too");
});

Deno.test("the runtime is copied in as athena.elf", async () => {
  const { root, files } = mockDir("newgame");
  const data = new Uint8Array([0x7f, 0x45, 0x4c, 0x46]);   // ELF magic
  const out = await A.fsScaffoldProject(root, samplePlan(), { name: "athena.elf", data });

  assert(out.written.includes("athena.elf"));
  assert(files.has("athena.elf"));
});

Deno.test("an existing runtime is left alone", async () => {
  const { root, files } = mockDir("newgame", { "athena.elf": "existing" });
  const out = await A.fsScaffoldProject(root, samplePlan(), { name: "athena.elf", data: new Uint8Array([1]) });
  assert(out.skipped.includes("athena.elf"));
  assertEquals(files.get("athena.elf"), "existing");
});

Deno.test("a scaffold with no runtime still lays the folder out", async () => {
  const { root, files } = mockDir("newgame");
  const out = await A.fsScaffoldProject(root, samplePlan(), null);
  assert(!files.has("athena.elf"));
  assertEquals(out.written.length, 4, "the rest of the scaffold should still be written");
});

Deno.test("emptiness is reported so the caller can warn before scaffolding", async () => {
  assertEquals(await A.fsIsEmpty(mockDir("fresh").root), true);
  assertEquals(await A.fsIsEmpty(mockDir("used", { "main.js": "// game\n" }).root), false);
});

Deno.test("export writes binary PNG assets byte for byte and skips identical images", async()=>{
  const {root,files}=mockDir(),result=exportResult({assets:[{filename:"textures/palette.png",dataUrl:"data:image/png;base64,AQIDBA=="},{filename:"3dmodels/cube.obj",content:"o Cube\n"}]});
  const first=await A.fsWriteExport(root,result);assert(first.written.includes("textures/palette.png"));assertEquals(files.get("textures/palette.png"),new Uint8Array([1,2,3,4]));
  const again=await A.fsWriteExport(root,result);assertEquals(again.written,[]);assert(again.unchanged.includes("textures/palette.png"));
});
Deno.test("declining a changed binary asset aborts the complete export",async()=>{
  const {root,files}=mockDir("game",{"textures/palette.png":new Uint8Array([99])});let conflicts;
  const result=exportResult({assets:[{filename:"textures/palette.png",dataUrl:"data:image/png;base64,AQID"}]});
  const out=await A.fsWriteExport(root,result,{confirmOverwrite:async list=>{conflicts=list;return false;}});assertEquals(out.skipped,true);assertEquals(files.get("textures/palette.png"),new Uint8Array([99]));assertEquals(files.has("main.js"),false);assertEquals(conflicts[0].path,"textures/palette.png");
});
