// FirstPersonController.js — generated by the First Person template.
//
// ctx.player is this object's own state slot. The only engine handle it needs
// is ctx.physics.bodies.player: there is no RenderObject, because the thing
// this script drives is the camera.

const DEADZONE = 25;      // sticks rest near 0 but are never exactly 0
const STICK_MAX = 127.0;

// Past about 80 degrees the view vector is nearly parallel to the camera's up
// vector and the look-at matrix loses its horizon. Stop short of it.
const PITCH_LIMIT = 1.35;

/** A stick axis as -1..1, with the rest position filtered out. */
function axis(v) {
    return (v > DEADZONE || v < -DEADZONE) ? Math.max(-1.0, Math.min(1.0, v / STICK_MAX)) : 0.0;
}

const numberBuffer = new Float64Array(1);
function number(value) { numberBuffer[0] = value; return numberBuffer[0]; }

export function init(ctx) {
    const s = ctx.player;
    s.yaw = 0.0;            // 0 looks along -Z, the direction the scene faces
    s.pitch = 0.0;          // radians, positive looks up
    s.speed = 5.0;          // world units per second
    s.lookRate = 2.6;       // radians per second at full stick
    s.jumpSpeed = 4.6;
    s.eyeHeight = 1.25;     // above the body's centre, not above the ground
    s.grounded = false;
    s.coyote = 0.0;
    s.jumpBuffer = 0.0;
    s.jumping = false;
    s.body = ctx.physics.bodies.player;
    s.cachedYaw = null;
    s.cachedPitch = null;
}

export function update(ctx, pad) {
    const s = ctx.player;
    const body = s.body;
    const dt = Math.max(0.001, Math.min(0.05, ctx.dt || 0.016));
    const p = body.getPosition();
    const vel = body.getLinearVel();
    let vy = number(vel[1]);

    // ── grounded ────────────────────────────────────────────────────
    // ode_onCollide stored the contact normal from the last step, so no extra
    // raycast is needed. Only its steepness is meaningful: ODE's normal points
    // into whichever geom the broad phase happened to call the first one, so
    // the sign is not ours to rely on — hence the abs().
    const n = s.lastHitNormal;
    const hit = s.lastHitPosition;
    s.grounded = !!n && Math.abs(n[1]) > 0.7 && (!hit || hit[1] < p[1]) && (!s.jumping || vy <= 0.0);
    s.lastHitNormal = null;     // consume it, or one contact grounds you forever
    if (s.grounded) s.jumping = false;
    s.coyote = s.grounded ? 0.10 : Math.max(0.0, s.coyote - dt);
    s.jumpBuffer = pad.justPressed(Pads.CROSS) ? 0.12 : Math.max(0.0, s.jumpBuffer - dt);

    // ── look ────────────────────────────────────────────────────────
    // Turning right decreases yaw: forward is (-sin yaw, 0, -cos yaw), so
    // world +X — the right-hand side of the screen — sits at yaw = -PI/2.
    let turn = axis(pad.rx);
    if (pad.pressed(Pads.L1)) turn = -1.0;   // fallback for a digital pad
    if (pad.pressed(Pads.R1)) turn =  1.0;
    s.yaw = number(s.yaw - turn * s.lookRate * dt);
    if (s.yaw > Math.PI) s.yaw = number(s.yaw - Math.PI * 2.0);
    if (s.yaw < -Math.PI) s.yaw = number(s.yaw + Math.PI * 2.0);
    // pad.ry grows downwards (it is rjoy_v - 127), so push-up must raise the aim.
    s.pitch = number(s.pitch - axis(pad.ry) * s.lookRate * dt);
    if (s.pitch >  PITCH_LIMIT) s.pitch =  PITCH_LIMIT;
    if (s.pitch < -PITCH_LIMIT) s.pitch = -PITCH_LIMIT;

    // A steady view needs no trigonometry. Invalidate when editable angles change.
    if (s.cachedYaw !== s.yaw) {
        s.cachedYaw = s.yaw;
        s.sinYaw = Math.sin(s.yaw); s.cosYaw = Math.cos(s.yaw);
    }
    const sy = s.sinYaw, cy = s.cosYaw;
    const fx = -sy, fz = -cy;   // forward, flattened onto the ground plane
    const rx =  cy, rz = -sy;   // right

    // ── move ────────────────────────────────────────────────────────
    let ix = axis(pad.lx);      // strafe
    let iz = -axis(pad.ly);     // forward; pad.ly grows downwards too
    if (pad.pressed(Pads.LEFT))  ix = -1.0;
    if (pad.pressed(Pads.RIGHT)) ix =  1.0;
    if (pad.pressed(Pads.UP))    iz =  1.0;
    if (pad.pressed(Pads.DOWN))  iz = -1.0;

    // Clamp to the unit circle so diagonals are not faster.
    const squared = number(ix * ix + iz * iz);
    if (squared > 1.0) { const mag = Math.sqrt(squared); ix /= mag; iz /= mag; }

    // Drive velocity directly and leave Y to gravity, except on the frame the
    // jump starts. Reading the current Y back keeps the fall going.
    if (s.coyote > 0.0 && s.jumpBuffer > 0.0) {
        vy = s.jumpSpeed;
        s.coyote = s.jumpBuffer = 0.0;
        s.grounded = false; s.jumping = true;
    }
    body.setLinearVel((fx * iz + rx * ix) * s.speed, vy, (fz * iz + rz * ix) * s.speed);

    // ── camera ──────────────────────────────────────────────────────
    // The scene's orbit rig is off, so nothing else writes the camera.
    // Target BEFORE position: Camera.target() moves the camera by the same
    // delta to preserve the view vector (setCameraTarget in src/camera.c), so
    // calling it second would drag the eye that was just placed.
    const ex = p[0], ey = p[1] + s.eyeHeight, ez = p[2];
    if (s.cachedPitch !== s.pitch) {
        s.cachedPitch = s.pitch;
        s.cosPitch = Math.cos(s.pitch); s.sinPitch = Math.sin(s.pitch);
    }
    const cp = s.cosPitch, sp = s.sinPitch;
    Camera.target(ex + fx * cp * 10.0, ey + sp * 10.0, ez + fz * cp * 10.0);
    Camera.position(ex, ey, ez);
}
