// SideScrollerController.js — generated by the Side Scroller template.
//
// Momentum platformer: progressive sprint, skids, rolls, charged launches,
// variable jumps, shoulder dash and ground pound. Controls:
// Left stick / D-pad: move. CROSS: jump (hold for height). R1: sprint.
// DOWN while moving: roll. DOWN + CROSS at rest: charge; release DOWN to launch.
// SQUARE: shoulder dash (once per airborne interval). DOWN in air: ground pound.
// ctx.player.tuning is editable. motion, speedTier and events are animation hooks;
// animation playback waits for the project's own model and clips.

const DEADZONE = 25;      // sticks rest near 0 but are never exactly 0
const STICK_MAX = 127.0;

// The play plane. Everything the character can touch is built on z = 0.
const PLANE_Z = 0.0;

// Athena's QuickJS arithmetic can return custom float32 values. Its mixed
// float32/float64 relational path reads a float32 as integer bits
// (quickjs.c js_relational_slow, float64_compare). Normalize values before
// comparisons with tuning values; reuse one buffer instead of string parsing.
const numberBuffer = new Float64Array(1);
function number(value) {
    numberBuffer[0] = value;
    return numberBuffer[0];
}

/** A stick axis as -1..1, with the rest position filtered out. */
function axis(v) {
    return (v > DEADZONE || v < -DEADZONE) ? Math.max(-1.0, Math.min(1.0, v / STICK_MAX)) : 0.0;
}

function approach(value, target, amount) {
    value = number(value);
    target = number(target);
    if (value < target) return Math.min(value + amount, target);
    return Math.max(value - amount, target);
}

export function init(ctx) {
    const s = ctx.player;
    s.jumpSpeed = 6.5;      // clears 2.1 units against gravity 9.81
    s.tuning = {
        walkSpeed: 5.0, runSpeed: 9.0, fastSpeed: 12.0, machSpeed: 16.0,
        fastAfter: 0.65, machAfter: 1.5,
        acceleration: 22.0, sprintAcceleration: 16.0, airAcceleration: 8.0,
        brake: 32.0, drag: 12.0, rollDrag: 1.8, rollBrake: 9.0, rollSlope: 1.8,
        rollMinSpeed: 2.0, rollStopSpeed: 0.8,
        chargeRate: 5.0, chargeTap: 2.0, chargeMax: 8.0, launchSpeed: 9.0,
        shortJumpSpeed: 2.8, coyoteTime: 0.10, jumpBuffer: 0.12, supportGrace: 0.05,
        fallGravity: 1.7, gravity: 9.81, terminalSpeed: 18.0,
        dashSpeed: 12.0, dashDuration: 0.20, dashCooldown: 0.35,
        slamSpeed: 18.0, slamRecovery: 0.10,
        lookAhead: 2.5, cameraResponse: 6.0,
    };
    s.facing = 1.0;         // +1 right, -1 left
    s.camDistance = 11.0;   // how far out on +Z the camera sits
    s.camHeight = 2.0;      // above the character
    s.camFloor = 2.5;       // never look below this, or the ground fills the screen
    s.grounded = false;
    s.motion = "idle";
    s.speedTier = 0;
    s.vx = 0.0;
    s.vy = 0.0;
    s.sprintTime = 0.0;
    s.coyote = 0.0;
    s.supportTime = 0.0;
    s.jumpBuffer = 0.0;
    s.jumping = false;
    s.jumpCut = false;
    s.rolling = false;
    s.charging = false;
    s.charge = 0.0;
    s.dashTimer = 0.0;
    s.dashCooldown = 0.0;
    s.dashVelocity = 0.0;
    s.airDashUsed = false;
    s.slamming = false;
    s.recovery = 0.0;
    s.wasDown = false;
    s.lookAhead = 0.0;
    s.events = { jump: false, land: false, dash: false, launch: false, slamLand: false };
    s.body = ctx.physics.bodies.player;
    s.view = ctx.RenderObjects.player;
    s.rotation = { x: 0.0, y: Math.PI * 0.5, z: 0.0 };
    s.view.rotation = s.rotation;
    s.drawFacing = s.facing;
    s.cameraX = s.cameraY = s.cameraDistance = null;
}

export function update(ctx, pad) {
    const s = ctx.player;
    const body = s.body;
    const view = s.view;
    const t = s.tuning;
    const dt = Math.max(0.001, Math.min(0.05, ctx.dt || 0.016));
    const vel = body.getLinearVel();
    const p = body.getPosition();
    let vx = number(vel[0]), vy = number(vel[1]);
    s.events.jump = s.events.land = s.events.dash = s.events.launch = s.events.slamLand = false;
    s.dashTimer = Math.max(0.0, s.dashTimer - dt);
    s.dashCooldown = Math.max(0.0, s.dashCooldown - dt);
    s.recovery = Math.max(0.0, s.recovery - dt);
    s.jumpBuffer = Math.max(0.0, s.jumpBuffer - dt);

    // ── grounded ────────────────────────────────────────────────────
    // ODE's contact normal depends on geom order (ath_ode.c contact_callback).
    // A previous support contact must not ground a character already rising.
    const n = s.lastHitNormal;
    const wasGrounded = s.grounded;
    const hitPosition = s.lastHitPosition;
    const support = !!n && Math.abs(n[1]) > 0.7 && (!hitPosition || hitPosition[1] < p[1] - 0.05);
    s.supportTime = support ? t.supportGrace : Math.max(0.0, s.supportTime - dt);
    // ODE's soft contacts can disappear for a frame while moving on a floor.
    // Recovery also cancels the engine's hardcoded bounce after a ground pound
    // (ath_ode.c contact_callback), rather than letting it launch the character.
    if (s.recovery > 0.0) vy = Math.min(vy, 0.0);
    s.grounded = s.supportTime > 0.0 && (!s.jumping || vy <= 0.0);
    s.lastHitNormal = null;     // consume it, or one contact grounds you forever
    if (s.grounded) {
        s.coyote = support ? t.coyoteTime : Math.max(0.0, s.coyote - dt);
        s.airDashUsed = false;
        s.jumping = false;
        if (!wasGrounded) {
            s.events.land = true;
            if (s.slamming) {
                s.events.slamLand = true;
                s.recovery = t.slamRecovery;
                s.rolling = false;
            }
        }
        s.slamming = false;
        vy = Math.min(vy, 0.0);
    } else s.coyote = Math.max(0.0, s.coyote - dt);

    // ── input ───────────────────────────────────────────────────────
    let ix = axis(pad.lx);
    if (pad.pressed(Pads.LEFT))  ix = -1.0;
    if (pad.pressed(Pads.RIGHT)) ix =  1.0;
    const vertical = number(axis(pad.ly));
    const down = pad.pressed(Pads.DOWN) || vertical > 0.5;
    const up = pad.pressed(Pads.UP) || vertical < -0.5;
    const sprint = pad.pressed(Pads.R1);
    const jumpPressed = pad.justPressed(Pads.CROSS);
    const jumpHeld = pad.pressed(Pads.CROSS);
    const dashPressed = pad.justPressed(Pads.SQUARE);
    const opposing = Math.abs(vx) > 0.1 && ix * vx < 0.0;
    let launched = false;

    // ── crouch, roll and charged launch ─────────────────────────────
    // These are movement states; the placeholder collider stays upright.
    if (s.grounded && down && Math.abs(vx) >= t.rollMinSpeed && !s.charging &&
        s.recovery === 0.0 && s.dashTimer === 0.0) s.rolling = true;
    if (s.grounded && down && Math.abs(vx) < t.rollMinSpeed && jumpPressed && s.dashTimer === 0.0) {
        s.charging = true;
        s.rolling = false;
        s.charge = Math.min(t.chargeMax, s.charge + t.chargeTap);
        s.jumpBuffer = 0.0;
    } else if (jumpPressed) s.jumpBuffer = t.jumpBuffer;
    if (s.charging) {
        if (!s.grounded) { s.charging = false; s.charge = 0.0; }
        else if (down) {
            s.charge = Math.min(t.chargeMax, s.charge + t.chargeRate * dt);
            vx = 0.0;
            if (Math.abs(ix) > 0.15) s.facing = ix > 0.0 ? 1.0 : -1.0;
        } else {
            vx = s.facing * (t.launchSpeed + s.charge);
            s.charging = false;
            s.charge = 0.0;
            s.rolling = true;
            s.events.launch = true;
            launched = true;
        }
    }
    if (up || (s.grounded && Math.abs(vx) < t.rollStopSpeed)) s.rolling = false;

    // ── shoulder dash and ground pound ──────────────────────────────
    if (!s.grounded && ((down && !s.wasDown) || (down && dashPressed))) {
        s.slamming = true;
        s.rolling = false;
        s.dashTimer = 0.0;
        s.coyote = 0.0;
        s.jumpBuffer = 0.0;
    }
    if (dashPressed && !down && !s.charging && !s.slamming && s.recovery === 0.0 &&
        s.dashCooldown === 0.0 && (s.grounded || !s.airDashUsed)) {
        if (Math.abs(ix) > 0.15) s.facing = ix > 0.0 ? 1.0 : -1.0;
        s.dashVelocity = s.facing * Math.max(t.dashSpeed, Math.abs(vx));
        s.dashTimer = t.dashDuration;
        s.dashCooldown = t.dashCooldown;
        s.events.dash = true;
        s.rolling = false;
        if (!s.grounded) s.airDashUsed = true;
    }

    // ── momentum ────────────────────────────────────────────────────
    if (s.grounded && sprint && Math.abs(ix) > 0.15 && !opposing && !down &&
        !s.rolling && !s.charging && s.recovery === 0.0) s.sprintTime = number(s.sprintTime + dt);
    else if (s.grounded || !sprint || opposing) s.sprintTime = 0.0;
    let maxSpeed = sprint ? t.runSpeed : t.walkSpeed;
    if (s.sprintTime >= t.fastAfter) maxSpeed = t.fastSpeed;
    if (s.sprintTime >= t.machAfter) maxSpeed = t.machSpeed;
    if (s.slamming) {
        vx = approach(vx, 0.0, t.airAcceleration * dt);
        vy = -t.slamSpeed;
    } else if (s.dashTimer > 0.0) vx = s.dashVelocity;
    else if (s.recovery > 0.0) vx = approach(vx, 0.0, t.brake * dt);
    else if (!s.charging && !launched) {
        if (s.rolling && s.grounded) {
            vx = approach(vx, 0.0, (opposing ? t.rollBrake : t.rollDrag) * dt);
            // Gravity projected onto the slope; nx * ny is unchanged when
            // ODE reverses geom order. Only roll gets this extra slope drive.
            if (support) vx += t.gravity * n[0] * n[1] * t.rollSlope * dt;
        }
        else if (s.grounded && down) vx = approach(vx, 0.0, t.brake * dt);
        else if (Math.abs(ix) > 0.0) {
            const target = ix * maxSpeed;
            const accel = s.grounded ? (opposing ? t.brake : (sprint ? t.sprintAcceleration : t.acceleration)) : t.airAcceleration;
            // Releasing sprint in air preserves speed; steer without resetting it.
            if (s.grounded || opposing || Math.abs(vx) < Math.abs(target)) {
                const rate = !opposing && Math.abs(vx) > Math.abs(target) ? t.drag : accel;
                vx = approach(vx, target, rate * dt);
            }
        } else if (s.grounded) vx = approach(vx, 0.0, t.drag * dt);
    }

    // ── forgiving, variable-height jump ─────────────────────────────
    if (s.jumpBuffer > 0.0 && s.coyote > 0.0 && !s.charging && !s.slamming && s.recovery === 0.0) {
        vy = s.jumpSpeed;
        s.grounded = false;
        s.supportTime = 0.0;
        s.coyote = 0.0;
        s.jumpBuffer = 0.0;
        s.jumping = true;
        s.jumpCut = false;
        s.events.jump = true;
    }
    if (s.jumping && !jumpHeld && !s.jumpCut && vy > 0.0) {
        vy = Math.min(vy, t.shortJumpSpeed);
        s.jumpCut = true;
    }
    // ODE applies ordinary gravity afterwards; add only the extra fall gravity.
    if (!s.grounded && vy < 0.0 && !s.slamming) {
        vy = Math.max(-t.terminalSpeed, vy - t.gravity * (t.fallGravity - 1.0) * dt);
    }
    // Z velocity is always zero: this is what keeps the game two-dimensional.
    body.setLinearVel(vx, vy, 0.0);
    s.vx = vx;
    s.vy = vy;
    s.wasDown = down;

    // ── animation contract ──────────────────────────────────────────
    s.speedTier = Math.abs(vx) >= t.machSpeed - 0.5 ? 4 : Math.abs(vx) >= t.fastSpeed - 0.5 ? 3 : Math.abs(vx) >= t.runSpeed - 0.5 ? 2 : Math.abs(vx) > 0.2 ? 1 : 0;
    if (s.slamming) s.motion = "slam";
    else if (s.charging) s.motion = "charge";
    else if (s.dashTimer > 0.0) s.motion = "dash";
    else if (s.recovery > 0.0) s.motion = "land";
    else if (s.rolling) s.motion = "roll";
    else if (!s.grounded) s.motion = vy > 0.0 ? "jump" : "fall";
    else if (down) s.motion = "crouch";
    else if (opposing && Math.abs(vx) > 1.0) s.motion = "skid";
    else if (s.speedTier >= 4) s.motion = "mach";
    else if (s.speedTier >= 3) s.motion = "sprint";
    else if (s.speedTier >= 2) s.motion = "run";
    else s.motion = s.speedTier > 0 ? "walk" : "idle";

    // A contact with the corner of a platform can still nudge the body off the
    // play plane before the next step reads the velocity back, so snap it.
    const drift = p[2] - PLANE_Z;
    if (drift > 0.001 || drift < -0.001) body.setPosition(p[0], p[1], PLANE_Z);

    // ── face the way you are running ────────────────────────────────
    // rotation.y = T sends the model's +Z axis to (sin T, cos T), so +PI/2
    // points it along world +X and -PI/2 along -X. Freeze Rotation keeps the
    // solver from touching this.
    // Keep facing the travel direction during a skid or roll.
    if (!s.charging && Math.abs(vx) > 0.2) s.facing = vx > 0.0 ? 1.0 : -1.0;
    else if (!s.charging && Math.abs(ix) > 0.15) s.facing = ix > 0.0 ? 1.0 : -1.0;
    // Direction has only two values. Rebuilding the native transform every
    // frame wastes matrix work and allocates an otherwise identical object.
    if (s.drawFacing !== s.facing) {
        s.drawFacing = s.facing;
        s.rotation.y = s.facing * Math.PI * 0.5;
        view.rotation = s.rotation;
    }

    // ── camera ──────────────────────────────────────────────────────
    // Follows X freely and Y only upward, so a jump does not make the whole
    // screen bob. Target BEFORE position: Camera.target() moves the camera by
    // the same delta to preserve the view vector (setCameraTarget in
    // src/camera.c), so calling it second would drag the position just set.
    const cy = Math.max(p[1] + s.camHeight, s.camFloor);
    const ahead = Math.max(-1.0, Math.min(1.0, vx / t.machSpeed)) * t.lookAhead;
    s.lookAhead += (ahead - s.lookAhead) * Math.min(1.0, t.cameraResponse * dt);
    const cx = p[0] + s.lookAhead;
    if (cx !== s.cameraX || cy !== s.cameraY || s.camDistance !== s.cameraDistance) {
        s.cameraX = cx; s.cameraY = cy; s.cameraDistance = s.camDistance;
        Camera.target(cx, cy, PLANE_Z);
        Camera.position(cx, cy, PLANE_Z + s.camDistance);
    }
}
