// ThirdPersonController.js — generated by the Third Person template.
//
// ctx.player is this object's own state slot. The engine handles it reaches
// are ctx.physics.bodies.player (the ODE body) and ctx.RenderObjects.player
// (what is drawn).

const DEADZONE = 25;      // sticks rest near 0 but are never exactly 0
const STICK_MAX = 127.0;

// The camera must stay off the poles: at 90 degrees the view vector lines up
// with the camera's up vector and the look-at matrix has no horizon left.
const PITCH_MIN = -0.2;
const PITCH_MAX = 1.2;

/** A stick axis as -1..1, with the rest position filtered out. */
function axis(v) {
    return (v > DEADZONE || v < -DEADZONE) ? Math.max(-1.0, Math.min(1.0, v / STICK_MAX)) : 0.0;
}

const numberBuffer = new Float64Array(1);
function number(value) { numberBuffer[0] = value; return numberBuffer[0]; }

export function init(ctx) {
    const s = ctx.player;
    s.yaw = 0.0;            // camera angle. 0 puts the camera on +Z, looking at -Z
    s.pitch = 0.35;         // radians above the character
    s.angle = Math.PI;      // model facing: PI points its +Z nose along world -Z
    s.speed = 6.0;          // world units per second
    s.turnRate = 12.0;      // how quickly the character swings around
    s.lookRate = 2.4;       // radians per second at full stick
    s.jumpSpeed = 5.2;
    s.camDistance = 8.0;
    s.camHeight = 1.5;      // where the camera looks, above the body centre
    s.grounded = false;
    s.coyote = 0.0;
    s.jumpBuffer = 0.0;
    s.jumping = false;
    s.body = ctx.physics.bodies.player;
    s.view = ctx.RenderObjects.player;
    s.rotation = { x: 0.0, y: s.angle, z: 0.0 };
    s.view.rotation = s.rotation;
    s.cachedYaw = null; s.cachedPitch = null;
    s.moveX = null; s.moveZ = null; s.wantAngle = s.angle;
}

export function update(ctx, pad) {
    const s = ctx.player;
    const body = s.body;
    const view = s.view;
    const dt = Math.max(0.001, Math.min(0.05, ctx.dt || 0.016));
    const p = body.getPosition();
    const vel = body.getLinearVel();
    let vy = number(vel[1]);

    // ── grounded ────────────────────────────────────────────────────
    // ode_onCollide stored the contact normal from the last step. Only its
    // steepness is meaningful: ODE's normal points into whichever geom the
    // broad phase called the first one, so the sign is not ours to rely on.
    const n = s.lastHitNormal;
    const hit = s.lastHitPosition;
    s.grounded = !!n && Math.abs(n[1]) > 0.7 && (!hit || hit[1] < p[1]) && (!s.jumping || vy <= 0.0);
    s.lastHitNormal = null;     // consume it, or one contact grounds you forever
    if (s.grounded) s.jumping = false;
    s.coyote = s.grounded ? 0.10 : Math.max(0.0, s.coyote - dt);
    s.jumpBuffer = pad.justPressed(Pads.CROSS) ? 0.12 : Math.max(0.0, s.jumpBuffer - dt);

    // ── swing the camera ────────────────────────────────────────────
    // Turning right decreases yaw: forward is (-sin yaw, 0, -cos yaw), so
    // world +X — the right-hand side of the screen — sits at yaw = -PI/2.
    let turn = axis(pad.rx);
    if (pad.pressed(Pads.L1)) turn = -1.0;   // fallback for a digital pad
    if (pad.pressed(Pads.R1)) turn =  1.0;
    s.yaw = number(s.yaw - turn * s.lookRate * dt);
    if (s.yaw > Math.PI) s.yaw = number(s.yaw - Math.PI * 2.0);
    if (s.yaw < -Math.PI) s.yaw = number(s.yaw + Math.PI * 2.0);
    // pad.ry grows downwards (it is rjoy_v - 127), and pitch is the camera's
    // elevation, so adding it means pushing the stick up drops the camera and
    // aims the view upward — the same gesture as in first person.
    s.pitch = number(s.pitch + axis(pad.ry) * s.lookRate * dt);
    if (s.pitch > PITCH_MAX) s.pitch = PITCH_MAX;
    if (s.pitch < PITCH_MIN) s.pitch = PITCH_MIN;

    if (s.cachedYaw !== s.yaw) {
        s.cachedYaw = s.yaw;
        s.sinYaw = Math.sin(s.yaw); s.cosYaw = Math.cos(s.yaw);
    }
    const sy = s.sinYaw, cy = s.cosYaw;
    const fx = -sy, fz = -cy;   // where the camera looks, flattened
    const rx =  cy, rz = -sy;   // its right

    // ── move, relative to the camera ────────────────────────────────
    let ix = axis(pad.lx);
    let iz = -axis(pad.ly);     // pad.ly grows downwards, so negate for "forward"
    if (pad.pressed(Pads.LEFT))  ix = -1.0;
    if (pad.pressed(Pads.RIGHT)) ix =  1.0;
    if (pad.pressed(Pads.UP))    iz =  1.0;
    if (pad.pressed(Pads.DOWN))  iz = -1.0;

    // Clamp to the unit circle so diagonals are not faster.
    const squared = number(ix * ix + iz * iz);
    if (squared > 1.0) { const mag = Math.sqrt(squared); ix /= mag; iz /= mag; }

    const mx = fx * iz + rx * ix;   // world direction of travel
    const mz = fz * iz + rz * ix;

    if (s.coyote > 0.0 && s.jumpBuffer > 0.0) {
        vy = s.jumpSpeed;
        s.coyote = s.jumpBuffer = 0.0;
        s.grounded = false; s.jumping = true;
    }
    body.setLinearVel(mx * s.speed, vy, mz * s.speed);

    // ── face the direction of travel ────────────────────────────────
    // rotation.y = T sends the model's +Z axis to (sin T, cos T), so the angle
    // that points its nose along (mx, mz) is atan2(mx, mz).
    // Freeze Rotation keeps the solver from touching this.
    if (squared > 0.0225) {
        if (mx !== s.moveX || mz !== s.moveZ) {
            s.moveX = mx; s.moveZ = mz; s.wantAngle = Math.atan2(mx, mz);
        }
        const want = s.wantAngle;
        let delta = number(want - s.angle);
        if (delta >  Math.PI) delta = number(delta - Math.PI * 2.0);
        if (delta < -Math.PI) delta = number(delta + Math.PI * 2.0);
        if (Math.abs(delta) > 0.001) {
            s.angle = number(s.angle + delta * Math.min(1.0, s.turnRate * dt));
            if (s.angle > Math.PI) s.angle = number(s.angle - Math.PI * 2.0);
            if (s.angle < -Math.PI) s.angle = number(s.angle + Math.PI * 2.0);
            s.rotation.y = s.angle;
            view.rotation = s.rotation;
        }
    }

    // ── camera ──────────────────────────────────────────────────────
    // Straight back along the camera's own forward vector, lifted by pitch.
    // Target BEFORE position: Camera.target() moves the camera by the same
    // delta to preserve the view vector (setCameraTarget in src/camera.c), so
    // calling it second would drag the position that was just set.
    const tx = p[0], ty = p[1] + s.camHeight, tz = p[2];
    if (s.cachedPitch !== s.pitch || s.cachedDistance !== s.camDistance) {
        s.cachedPitch = s.pitch; s.cachedDistance = s.camDistance;
        s.back = s.camDistance * Math.cos(s.pitch);
        s.lift = s.camDistance * Math.sin(s.pitch);
    }
    const back = s.back;
    Camera.target(tx, ty, tz);
    Camera.position(tx - fx * back, ty + s.lift, tz - fz * back);
}
