// TopDownController.js — generated by the Top Down template.
//
// ctx.player is this object's own state slot. The engine handles it reaches
// are ctx.physics.bodies.player (the ODE body) and ctx.RenderObjects.player
// (what is drawn).

const DEADZONE = 25;      // sticks rest near 0 but are never exactly 0
const STICK_MAX = 127.0;

function axis(v) {
    return (v > DEADZONE || v < -DEADZONE) ? Math.max(-1.0, Math.min(1.0, v / STICK_MAX)) : 0.0;
}
const numberBuffer = new Float64Array(1);
function number(value) { numberBuffer[0] = value; return numberBuffer[0]; }

export function init(ctx) {
    const s = ctx.player;
    s.speed = 6.0;          // world units per second
    s.turnRate = 12.0;      // how quickly the character swings around
    s.angle = 0.0;
    s.camHeight = 13.0;
    s.camDistance = 9.0;
    s.body = ctx.physics.bodies.player;
    s.view = ctx.RenderObjects.player;
    s.rotation = { x: 0.0, y: s.angle, z: 0.0 };
    s.view.rotation = s.rotation;
    s.moveX = null; s.moveZ = null; s.wantAngle = s.angle;
}

export function update(ctx, pad) {
    const s = ctx.player;
    const body = s.body;
    const view = s.view;
    const dt = Math.max(0.001, Math.min(0.05, ctx.dt || 0.016));

    // ── read the stick, fall back to the d-pad ──────────────────────
    let ix = axis(pad.lx);
    // World -Z is screen-up. Negative pad.ly already points along -Z.
    let iz = axis(pad.ly);

    if (pad.pressed(Pads.LEFT))  ix = -1.0;
    if (pad.pressed(Pads.RIGHT)) ix =  1.0;
    if (pad.pressed(Pads.UP))    iz = -1.0;
    if (pad.pressed(Pads.DOWN))  iz =  1.0;

    // Clamp to the unit circle so diagonals are not faster.
    const squared = number(ix * ix + iz * iz);
    if (squared > 1.0) { const mag = Math.sqrt(squared); ix /= mag; iz /= mag; }

    // ── move ────────────────────────────────────────────────────────
    // Drive velocity directly and leave Y to gravity. Forward on the stick
    // means -Z, which is the direction the camera looks.
    const vel = body.getLinearVel();
    body.setLinearVel(ix * s.speed, vel[1], iz * s.speed);

    // ── face the direction of travel ────────────────────────────────
    // Freeze Rotation keeps the solver from touching this.
    if (squared > 0.0225) {
        if (ix !== s.moveX || iz !== s.moveZ) {
            s.moveX = ix; s.moveZ = iz; s.wantAngle = Math.atan2(ix, iz);
        }
        const want = s.wantAngle;
        let delta = number(want - s.angle);
        if (delta >  Math.PI) delta = number(delta - Math.PI * 2.0);
        if (delta < -Math.PI) delta = number(delta + Math.PI * 2.0);
        if (Math.abs(delta) > 0.001) {
            s.angle = number(s.angle + delta * Math.min(1.0, s.turnRate * dt));
            if (s.angle > Math.PI) s.angle = number(s.angle - Math.PI * 2.0);
            if (s.angle < -Math.PI) s.angle = number(s.angle + Math.PI * 2.0);
            s.rotation.y = s.angle;
            view.rotation = s.rotation;
        }
    }

    // ── camera ──────────────────────────────────────────────────────
    // The scene's orbit rig is off, so nothing else writes the camera.
    // Target BEFORE position: Camera.target() moves the camera by the same
    // delta to preserve the view vector (setCameraTarget in src/camera.c), so
    // calling it second would drag the position that was just set.
    const p = view.position;
    Camera.target(p.x, p.y, p.z);
    Camera.position(p.x, p.y + s.camHeight, p.z + s.camDistance);
}
