// ═══════════════════════════════════════════════════════════════════════
//  GENERATE — assembles main.js from the resolved scene
//
//  Declaration order matters and is enforced here:
//    models -> physics -> shadows   (shadow raycasting needs ode_space)
//    ... -> ctx                     (ctx references everything above)
//    everything -> the frame loop   (nothing is declared inside it)
// ═══════════════════════════════════════════════════════════════════════

const PSM_PRESETS = {
  CT32_Z32: ["Screen.CT32", "Screen.Z32"],
  CT32_Z24: ["Screen.CT32", "Screen.Z24"],
  CT16S_Z16S: ["Screen.CT16S", "Screen.Z16S"],
};

function generateProject(project, uploadedFiles = [], { sceneId } = {}) {
  const scenes = project.scenes || [], files = editorAssets(project, uploadedFiles);
  const entry = scenes.find(s => s.id === (sceneId || project.startSceneId)) || scenes[0];
  if (!entry) return { main: "// No scene to export.\n", scripts: [], sceneFiles: [], assets: [], stats: {}, diagnostics: [{ level: "error", message: "The project has no scenes." }] };
  const scenePaths = new Map(scenes.map((s, i) => [s.id, `scene_${i + 1}_${ident(s.name, "level").slice(0, 48)}.js`]));
  const outputs = scenes.map(scene => ({ scene, result: generateSceneProgram(project, scene, files, scenePaths) }));
  const main = outputs.find(o => o.scene === entry).result.main;
  const merge = key => [...new Map(outputs.flatMap(o => o.result[key]).map(f => [f.filename, f])).values()];
  const diagnostics = outputs.flatMap(({ scene, result }) => result.diagnostics.map(d => ({ ...d, sceneId: scene.id, sceneName: scene.name })));
  // Asset references use names. Reject ambiguous inputs before editorAssets
  // merges disk files with the project's deliberate working-copy overrides.
  for (const group of [uploadedFiles, project.assets || [], project.scripts || []]) {
    const names = new Map();
    for (const file of group) {
      const key = String(file.name).toLowerCase(), previous = names.get(key);
      if (previous && (previous.sourcePath !== file.sourcePath || previous.cat !== file.cat ||
          previous.content !== file.content || previous.dataUrl !== file.dataUrl)) {
        diagnostics.push({ level: "error", message: `More than one asset is named "${file.name}". Rename one of the files and update its references before exporting.` });
      }
      names.set(key, file);
    }
  }
  const stats = {};
  for (const { result } of outputs) for (const [key, value] of Object.entries(result.stats)) stats[key] = (stats[key] || 0) + value;
  const assets = merge("assets"), scripts = merge("scripts");
  const destinations = new Set(["main.js", "athena.ini", "athena.elf"]);
  for (const file of [...scripts, ...assets, ...(scenes.length > 1 ? outputs.map(o => ({ filename: scenePaths.get(o.scene.id) })) : [])]) {
    const path = file.filename.toLowerCase();
    if (!usableExportPath(file.filename)) diagnostics.push({ level: "error", message: `"${file.filename}" is not a usable filename. Rename the file before exporting.` });
    if (destinations.has(path)) diagnostics.push({ level: "error", message: `Two files would overwrite "${file.filename}". Rename the asset or change its folder.` });
    destinations.add(path);
  }
  return { main, scripts, assets, diagnostics, stats, sceneCount: scenes.length,
    sceneFiles: scenes.length > 1 ? outputs.map(o => ({ filename: scenePaths.get(o.scene.id), content: o.result.main })) : [] };
}

function generateSceneProgram(project, scene, uploadedFiles, scenePaths) {
  if (!scene) {
    return { main: "// No scene to export.\n", scripts: [], diagnostics: [
      { level: "error", message: "The project has no scenes." },
    ] };
  }

  const ir = resolveScene(project, scene, editorAssets(project, uploadedFiles));
  const e = new Emitter();

  // ── header ───────────────────────────────────────────────────────────
  e.w(`// ${"═".repeat(66)}`);
  e.w(`// ${String(project.name).replace(/[\r\n\u2028\u2029]/g, " ")} — ${String(scene.name).replace(/[\r\n\u2028\u2029]/g, " ")}`);
  e.w(`// Generated by AthEditor. Edits here are overwritten`);
  e.w(`// on the next export; put your own logic in ${ir.dirs.scripts}/.`);
  e.w(`// ${"═".repeat(66)}`);
  e.nl();

  for (const f of ir.scripts.files) {
    e.w(`import * as behaviour_${f.alias} from "./${jsStr(ir.dirs.scripts)}/${jsStr(f.name)}";`);
    e.w(`const init_${f.alias} = typeof behaviour_${f.alias}.init === "function" ? behaviour_${f.alias}.init : () => {};`);
    e.w(`const update_${f.alias} = typeof behaviour_${f.alias}.update === "function" ? behaviour_${f.alias}.update : () => {};`);
  }
  if (ir.scripts.files.length) e.nl();

  // ── display ──────────────────────────────────────────────────────────
  // These are project settings, not scene settings: a PS2 program calls
  // Screen.setMode exactly once, so they cannot meaningfully differ per level.
  const D = project.display || {};
  const AT = D.alphaTest || {};

  e.section("Display");
  e.w(`Screen.setFrameCounter(${D.frameCounter !== false});`);
  e.w(`Screen.setVSync(${D.vsync !== false});`);
  e.nl();
  const [psmColor, psmDepth] = D.psm === "custom"
    ? [D.psmCustomColor || "Screen.CT16S", D.psmCustomDepth || "Screen.Z16S"]
    : (PSM_PRESETS[D.psm || "CT16S_Z16S"] || PSM_PRESETS.CT16S_Z16S);
  e.w(`const canvas = Screen.getMode();`);
  // Blank means "leave the console's own video mode alone".
  if (D.mode) e.w(`canvas.mode = Screen.${D.mode};`);
  e.w(`canvas.zbuffering = true;`);
  e.w(`canvas.psm  = ${psmColor};`);
  e.w(`canvas.psmz = ${psmDepth};`);
  e.w(`Screen.setMode(canvas);`);
  e.nl();
  e.w(`Render.init();`);
  e.w(`Render.setView(${fl(ir.camera.fov)}, ${fl(ir.camera.near)}, ${fl(ir.camera.far)});`);
  e.nl();
  // Wrap the existing screen surfaces once, shared by sky and shadow passes.
  // Screen.initBuffers creates JS wrappers; it does not allocate extra VRAM.
  if (ir.skybox || ir.shadowPasses.length) {
    e.w(`Screen.initBuffers();`);
    e.w(`const _mainDepth = Screen.getBuffer(Screen.DEPTH_BUFFER);`);
    e.nl();
  }
  // The overlay font is the one baked into the ELF unless the project folder
  // actually has a font file. Naming a file that is not there kills the
  // program at startup, which is a miserable way to greet a new project.
  const showOverlay = D.frameCounter !== false || !!D.debugHUD;
  if (showOverlay && ir.overlayFont) {
    e.w(`os.chdir("${jsStr(ir.dirs.fonts)}");`);
    e.w(`const font = new Font("${jsStr(ir.overlayFont)}");`);
    e.w(`os.chdir("..");`);
  } else if (showOverlay) {
    e.w(`const font = new Font("default");`);
  }
  if (showOverlay) {
    e.w(`font.scale = 0.6;`);
    e.w(`font.outline = 1.0;`);
    e.w(`font.outline_color = Color.new(0, 0, 0);`);
    e.comment("Refresh diagnostics every 15 frames; draw cached text every frame.");
    e.w(`let _hudFrame = 15, _hudText = "0 FPS", _hudMemory = "";`);
    e.nl();
  }
  const bg = scene.background || { r: 40, g: 40, b: 40, a: 128 };
  e.w(`const gray = Color.new(${il(bg.r)}, ${il(bg.g)}, ${il(bg.b)}, ${il(bg.a ?? 128)});`);
  e.nl();
  // Target first: setCameraTarget (src/camera.c) drags the camera by the
  // target delta to preserve the view vector, so it would move a position set
  // before it. Camera.position is a plain setter and does not move the target.
  e.w(`Camera.target(${f3(ir.camera.target.x)}, ${f3(ir.camera.target.y)}, ${f3(ir.camera.target.z)});`);
  e.w(`Camera.position(${f3(ir.camera.position.x)}, ${f3(ir.camera.position.y)}, ${f3(ir.camera.position.z)});`);
  e.nl();

  if (AT.enabled !== false) {
    e.section("Alpha test");
    e.w(`Screen.setParam(Screen.ALPHA_TEST_ENABLE, true);`);
    e.w(`Screen.setParam(Screen.ALPHA_TEST_METHOD, Screen.${AT.method || "ALPHA_GREATER"});`);
    e.w(`Screen.setParam(Screen.ALPHA_TEST_REF, ${il(AT.ref ?? 50)});`);
    e.w(`Screen.setParam(Screen.ALPHA_TEST_FAIL, Screen.${AT.onFail || "ALPHA_FAIL_NO_UPDATE"});`);
    e.w(`Screen.setParam(Screen.PIXEL_ALPHA_BLEND_ENABLE, ${AT.pixelBlend !== false});`);
    e.nl();
  }

  // ── resources ────────────────────────────────────────────────────────
  emitLights(e, ir);
  emitRenderDatas(e, ir);
  emitSkyboxSetup(e, ir);
  emitSounds(e, ir);
  emitPhysicsSetup(e, ir);   // before shadows: enableRaycast needs ode_space
  emitShadowSetup(e, ir);
  emitUI(e, ir);
  // The release's main.js requires reload at outer scope: destroying the VM
  // inside a behaviour's call stack leaks live objects and can hang. Queue
  // the destination here and restart only after the script returns.
  e.w(`let _nextScene = null;`);
  e.w(`function goToScene(name) {`);
  e.block(b => {
    const used = new Set();
    for (const transition of scene.transitions || []) {
      if (typeof transition.name !== "string" || !transition.name.trim()) {
        e.diagnostics.push({ level: "error", message: "An exit has no name. Enter its name in Scene settings → Transitions." });
        continue;
      }
      const path = scenePaths.get(transition.targetSceneId);
      if (!path) { e.diagnostics.push({ level: "error", message: `Exit "${transition.name}" points to a scene that no longer exists.` }); continue; }
      if (used.has(transition.name)) { e.diagnostics.push({ level: "error", message: `Two exits are named "${transition.name}". Give each exit a different name.` }); continue; }
      used.add(transition.name);
      b.w(`if (name === "${jsStr(transition.name)}") { _nextScene = "${jsStr(project.scenes.length > 1 ? path : "main.js")}"; return true; }`);
    }
    b.w(`return false;`);
  });
  e.w(`}`);
  emitCtx(e, ir);
  emitCtxUI(e, ir);

  // ── behaviours ───────────────────────────────────────────────────────
  if (ir.scripts.bindings.length) {
    e.section("Behaviours");
    const inited = new Set();
    for (const b of ir.scripts.bindings) {
      if (inited.has(b.entry.alias)) continue;
      inited.add(b.entry.alias);
      e.w(`init_${b.entry.alias}(ctx);`);
    }
    e.nl();
  }

  e.w(`let pad = Pads.get();`);
  e.w(`let lx = 0.0, ly = 0.0;`);
  e.nl();

  // ── frame loop ───────────────────────────────────────────────────────
  e.section("Frame loop");
  const frameHas3D = !!(ir.models.length || ir.shadows.length || ir.skybox || ir.scripts.files.length);
  if (!frameHas3D) e.w(`Screen.setParam(Screen.DEPTH_TEST_ENABLE, false);`);
  // The module must finish evaluating before its VM can be freed.
  // Screen.display runs frames from js_std_loop after module evaluation;
  // reloading inside a top-level infinite loop trips JS_FreeRuntime's live
  // object assertion on the shipped ELF (verified by verify-levels.js).
  e.w(`Screen.clearColor(gray);`);
  e.w(`Screen.display(() => {`);
  e.block((b) => {
    b.w(`if (_nextScene !== null) std.reload(_nextScene);`);
    b.w(`pad.update();`);
    if (ir.scripts.files.length) {
      b.w(`ctx.pad = pad;`);
      b.w(`ctx.frame++;`);
    }
    b.nl();

    const camScripted = !!ir.camera.obj?.components?.script?.file;
    if (scene.defaultCameraRig !== false && !camScripted) {
      b.comment("Default orbit camera — add a Script to the Camera object to take over");
      b.w(`lx = ((pad.lx > 25 || pad.lx < -25) ? pad.lx : 0) / 1024.0;`);
      b.w(`ly = ((pad.ly > 25 || pad.ly < -25) ? pad.ly : 0) / 1024.0;`);
      b.w(`if (lx !== 0.0 || ly !== 0.0) Camera.orbit(lx, ly);`);
      b.w(`if (pad.pressed(Pads.R2)) Camera.zoom(0.2);`);
      b.w(`else if (pad.pressed(Pads.L2)) Camera.zoom(-0.2);`);
      b.nl();
    }
    b.w(`if (pad.justPressed(Pads.TRIANGLE)) std.reload("main.js");`);
    b.nl();

    if (ir.scripts.bindings.length) {
      b.comment("Behaviour updates");
      const done = new Set();
      for (const bind of ir.scripts.bindings) {
        if (done.has(bind.entry.alias)) continue;
        done.add(bind.entry.alias);
        b.w(`update_${bind.entry.alias}(ctx, pad);`);
      }
      b.nl();

      // Convenience binding: a script that writes ctx.<key>.x/y/z moves its
      // object without touching RenderObjects directly.
      const movable = ir.scripts.bindings.filter((x) => x.modelVN);
      if (movable.length) {
        b.comment("ctx.<name>.x/y/z shortcut — write those and the object follows");
        for (const m of movable) {
          b.w(`if (ctx.${m.ctxKey}.x !== undefined) ${m.modelVN}.position = ` +
            `{x: ctx.${m.ctxKey}.x, y: ctx.${m.ctxKey}.y || 0, z: ctx.${m.ctxKey}.z || 0};`);
        }
        b.nl();
      }
    }

    emitPhysicsStep(b, ir);

    b.comment("Rendering");
    if (frameHas3D) b.w(`Camera.update();`);
    b.nl();
    emitSkyboxDraw(b, ir);

    if (ir.shadowPasses.length) {
      b.w(`_shadowPass();`);
      b.nl();
    }

    if (frameHas3D) {
      b.w(`Screen.setParam(Screen.DEPTH_TEST_ENABLE, true);`);
      b.w(`Screen.setParam(Screen.DEPTH_TEST_METHOD, Screen.DEPTH_GEQUAL);`);
    }
    b.nl();

    emitModelDraws(b, ir);
    emitShadowDraws(b, ir);

    if (frameHas3D) b.w(`Screen.setParam(Screen.DEPTH_TEST_ENABLE, false);`);
    b.nl();

    if (ir.ui.length) { b.w(`drawUI();`); b.nl(); }

    if (showOverlay) {
      b.w(`if (++_hudFrame >= 15) {`);
      b.block(h => {
        h.w(`_hudFrame = 0;`);
        h.w(`_hudText = Screen.getFPS(60) + " FPS";`);
        if (D.debugHUD) {
          h.w(`_hudText += "  " + Math.floor(System.getMemoryStats().used / 1048576) + " MB RAM";`);
          h.w(`_hudMemory = "VRAM static " + (Screen.getMemoryStats(Screen.VRAM_USED_STATIC) / 1024) +`);
          h.w(`    " KB  dynamic " + (Screen.getMemoryStats(Screen.VRAM_USED_DYNAMIC) / 1024) + " KB";`);
        }
      });
      b.w(`}`);
      b.w(`font.print(10, 10, _hudText);`);
      if (D.debugHUD) b.w(`font.print(10, 26, _hudMemory);`);
    }
    b.nl();

  });
  e.w(`});`);

  return {
    main: e.toString(),
    scripts: [...new Map([...ir.scripts.files, ...editorAssets(project, uploadedFiles).filter(f => f.cat === "scripts" && typeof f.content === "string")].map(f => [f.name, f])).values()].map(f => ({ filename: `${ir.dirs.scripts}/${f.name}`, content: f.content })),
    assets: [...editorAssets(project, uploadedFiles).filter(f => f.cat !== "scripts" && (f.content !== undefined || f.dataUrl)).map(f => ({filename: `${project.dirs?.[f.cat] || f.folder || f.cat}/${f.name}`, content:f.content, dataUrl:f.dataUrl})),
      ...(ir.skybox ? [{ filename: `${ir.dirs.models}/${ir.skybox.mesh}`, content: skyboxMeshOBJ() }] : [])],
    diagnostics: [...ir.diagnostics, ...e.diagnostics, ...exportAssetProblems(scene, uploadedFiles, project),
      ...validateScene(scene, uploadedFiles, project).filter(d => d.level === "error")],
    stats: {
      models: ir.models.length,
      renderDatas: ir.renderDatas.length,
      lights: ir.lights.length,
      bodies: ir.physics.bodies.length,
      shadows: ir.shadows.length,
      uiElements: ir.ui.length,
      vramLocked: ir.rtBytes,
    },
  };
}

function usableExportPath(path) {
  return typeof path === "string" && !!path && !/[\\:<>"|?*\x00-\x1f]/.test(path) &&
    path.split("/").every(part => part && part !== "." && part !== ".." && !/[. ]$/.test(part) &&
      !/^(con|prn|aux|nul|com[0-9]|lpt[0-9])(?:\.|$)/i.test(part));
}
